### PR TITLE
Add support for custom rules dirs

### LINKED ISSUE #68: How to set options.rulePaths or --rulesdir
Our project has some rules we created and they are stored in a specific location.

I need a way to provide this path through either the options object or eslint arguments.

Can this be accomplished using this plugin?

### PR DESCRIPTION
**Pull request by apexskier**
Resolves #68

@markholland

### CODE REVIEW

**Comment by markholland** [comment]
If I set a Rules Directory in extension preferences everything works as expected but if I set the same directory in Project Settings instead then no linting appears to be happening.

I'm always using the browse button when adding a Rules Directory.

Edit: If I add an absolute path to Project Settings it works. Using browse from Project Settings as I'd expect it adds a relative path but that appears to lead to no linting. The relative project path is `.eslint/rules` if this helps to know.

**Comment by apexskier** [comment]
Very weird - this is the underlying bug for the issue you found - https://github.com/gkz/optionator/issues/34

**Comment by apexskier** [comment]
@markholland Can you test once more? I added a workaround for the underlying issue. After digging around in the dependencies eslint uses for options parsing, I don't expect a root cause fix to come any time soon, but this should work.

**Comment by markholland** [comment]
Yes, this is now working with relative paths in Project Settings.

**Pull request merged**
